[2025-02-02T06:17:48.579+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:17:48.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/branch_dim_generator_dag.py for tasks to queue
[2025-02-02T06:17:48.584+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:17:48.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:17:48.590+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:17:48.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator_dag.py", line 10, in <module>
    from scripts.branch_dim_generator import generate_branch_dim_data
ModuleNotFoundError: No module named 'scripts.branch_dim_generator'
[2025-02-02T06:17:48.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:17:48.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/branch_dim_generator_dag.py took 0.048 seconds
[2025-02-02T06:18:18.696+0000] {processor.py:186} INFO - Started process (PID=481) to work on /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:18:18.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/branch_dim_generator_dag.py for tasks to queue
[2025-02-02T06:18:18.699+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:18.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:18:18.708+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:18.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator_dag.py", line 10, in <module>
    from scripts.branch_dim_generator import generate_branch_dim_data
ModuleNotFoundError: No module named 'scripts.branch_dim_generator'
[2025-02-02T06:18:18.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:18:18.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/branch_dim_generator_dag.py took 0.045 seconds
[2025-02-02T06:18:49.256+0000] {processor.py:186} INFO - Started process (PID=787) to work on /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:18:49.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/branch_dim_generator_dag.py for tasks to queue
[2025-02-02T06:18:49.259+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:49.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:18:49.263+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:18:49.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator_dag.py", line 10, in <module>
    from scripts.branch_dim_generator import generate_branch_dim_data
ModuleNotFoundError: No module named 'scripts.branch_dim_generator'
[2025-02-02T06:18:49.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:18:49.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/branch_dim_generator_dag.py took 0.034 seconds
[2025-02-02T06:19:19.631+0000] {processor.py:186} INFO - Started process (PID=1093) to work on /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:19:19.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/branch_dim_generator_dag.py for tasks to queue
[2025-02-02T06:19:19.635+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:19.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:19:19.637+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:19.636+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator_dag.py", line 10, in <module>
    from scripts.branch_dim_generator import generate_branch_dim_data
ModuleNotFoundError: No module named 'scripts.branch_dim_generator'
[2025-02-02T06:19:19.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:19:19.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/branch_dim_generator_dag.py took 0.035 seconds
[2025-02-02T06:19:49.970+0000] {processor.py:186} INFO - Started process (PID=1399) to work on /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:19:49.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/branch_dim_generator_dag.py for tasks to queue
[2025-02-02T06:19:49.972+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:49.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:19:49.975+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:19:49.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator_dag.py", line 10, in <module>
    from scripts.branch_dim_generator import generate_branch_dim_data
ModuleNotFoundError: No module named 'scripts.branch_dim_generator'
[2025-02-02T06:19:49.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:19:49.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/branch_dim_generator_dag.py took 0.033 seconds
[2025-02-02T06:20:20.206+0000] {processor.py:186} INFO - Started process (PID=1705) to work on /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:20:20.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/branch_dim_generator_dag.py for tasks to queue
[2025-02-02T06:20:20.209+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:20:20.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:20:20.211+0000] {logging_mixin.py:190} INFO - [2025-02-02T06:20:20.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/branch_dim_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/branch_dim_generator_dag.py", line 10, in <module>
    from scripts.branch_dim_generator import generate_branch_dim_data
ModuleNotFoundError: No module named 'scripts.branch_dim_generator'
[2025-02-02T06:20:20.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/branch_dim_generator_dag.py
[2025-02-02T06:20:20.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/branch_dim_generator_dag.py took 0.033 seconds
